name: Test
on: [push, pull_request]

jobs:
    test_project:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: ['20', '22']
        name: Node ${{ matrix.node }} Tests
        timeout-minutes: 8
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node }}
            - name: Npm install
              run: npm ci
            - name: Npm Lint
              run: npm run lint
            #- name: Npm Docs
            #  run: |
            #      npm run docs
            #      npm run build:readme
            - name: Upload coverage to Codecov Monorepo
              uses: codecov/codecov-action@v5.3.1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  name: Test
                  fail_ci_if_error: false
                  verbose: false
    status-check:
        name: Finish Test
        if: always()
        needs:
            - test_project
        runs-on: ubuntu-latest
        steps:
            - uses: re-actors/alls-green@v1.2.2
              with:
                  jobs: ${{ toJSON(needs) }}
